imports:
 - basic.yml
 - jobs/deploy.yml

UDC_Deploy:
  job:
    baseName: UDC_Deploy_Application
    baseClassName: UdcDeployApplication
    deployScript: "jobdsl/deploy/bash/UDC_Deploy_App.sh"
    destroyScript: "jobdsl/deploy/bash/UDC_Destroy.sh"
