imports:
 - basic.yml
 - jobs/deploy.yml

UDC_Deploy:
  job:
    baseName: UDC_Deploy
    baseClassName: UdcDeploy
    shellScript: "jobdsl/deploy/bash/UDC_Deploy.sh"

UDC_Destroy:
  job:
    baseName: UDC_Destroy
    baseClassName: UdcDestroy
    shellScript: "jobdsl/deploy/bash/UDC_Destroy.sh"
