imports:
 - basic.yml
 - jobs/deploy.yml

UDC_Deploy_LLE:
  job:
    baseName: UDC_Deploy_LLE
    baseClassName: UdcDeploy
    shellScript: "jobdsl/deploy/bash/UDC_Deploy.sh"
    setDescriptionScript: "jobdsl/deploy/groovy/setDescription.groovy"
    releaseName: stage

UDC_Destroy_LLE:
  job:
    baseName: UDC_Destroy_LLE
    baseClassName: UdcDestroy
    shellScript: "jobdsl/deploy/bash/UDC_Destroy.sh"
    releaseName: stage

UDC_Deploy_PROD:
  job:
    baseName: UDC_Deploy_PROD
    baseClassName: UdcDeploy
    shellScript: "jobdsl/deploy/bash/UDC_Deploy.sh"
    setDescriptionScript: "jobdsl/deploy/groovy/setDescription.groovy"
    releaseName: production

UDC_Destroy_PROD:
  job:
    baseName: UDC_Destroy_PROD
    baseClassName: UdcDestroy
    shellScript: "jobdsl/deploy/bash/UDC_Destroy.sh"
    releaseName: production

